package fabricruntime

// enum FABRIC_SERVICE_PARTITION_KIND
var FABRIC_SERVICE_PARTITION_KIND = struct {
	FABRIC_SERVICE_PARTITION_KIND_INVALID     int32
	FABRIC_SERVICE_PARTITION_KIND_SINGLETON   int32
	FABRIC_SERVICE_PARTITION_KIND_INT64_RANGE int32
	FABRIC_SERVICE_PARTITION_KIND_NAMED       int32
}{
	FABRIC_SERVICE_PARTITION_KIND_INVALID:     0,
	FABRIC_SERVICE_PARTITION_KIND_SINGLETON:   1,
	FABRIC_SERVICE_PARTITION_KIND_INT64_RANGE: 2,
	FABRIC_SERVICE_PARTITION_KIND_NAMED:       3,
}

// enum FABRIC_FAULT_TYPE
var FABRIC_FAULT_TYPE = struct {
	FABRIC_FAULT_TYPE_INVALID   int32
	FABRIC_FAULT_TYPE_PERMANENT int32
	FABRIC_FAULT_TYPE_TRANSIENT int32
}{
	FABRIC_FAULT_TYPE_INVALID:   0,
	FABRIC_FAULT_TYPE_PERMANENT: 1,
	FABRIC_FAULT_TYPE_TRANSIENT: 2,
}

// enum FABRIC_REPLICA_OPEN_MODE
var FABRIC_REPLICA_OPEN_MODE = struct {
	FABRIC_REPLICA_OPEN_MODE_INVALID  int32
	FABRIC_REPLICA_OPEN_MODE_NEW      int32
	FABRIC_REPLICA_OPEN_MODE_EXISTING int32
}{
	FABRIC_REPLICA_OPEN_MODE_INVALID:  0,
	FABRIC_REPLICA_OPEN_MODE_NEW:      1,
	FABRIC_REPLICA_OPEN_MODE_EXISTING: 2,
}

// enum FABRIC_SERVICE_PARTITION_ACCESS_STATUS
var FABRIC_SERVICE_PARTITION_ACCESS_STATUS = struct {
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_INVALID                 int32
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_GRANTED                 int32
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_RECONFIGURATION_PENDING int32
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_NOT_PRIMARY             int32
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_NO_WRITE_QUORUM         int32
}{
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_INVALID:                 0,
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_GRANTED:                 1,
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_RECONFIGURATION_PENDING: 2,
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_NOT_PRIMARY:             3,
	FABRIC_SERVICE_PARTITION_ACCESS_STATUS_NO_WRITE_QUORUM:         4,
}

// enum FABRIC_SECURITY_CREDENTIAL_KIND
var FABRIC_SECURITY_CREDENTIAL_KIND = struct {
	FABRIC_SECURITY_CREDENTIAL_KIND_NONE    int32
	FABRIC_SECURITY_CREDENTIAL_KIND_X509    int32
	FABRIC_SECURITY_CREDENTIAL_KIND_WINDOWS int32
	FABRIC_SECURITY_CREDENTIAL_KIND_CLAIMS  int32
	FABRIC_SECURITY_CREDENTIAL_KIND_X509_2  int32
	FABRIC_SECURITY_CREDENTIAL_KIND_INVALID int32
}{
	FABRIC_SECURITY_CREDENTIAL_KIND_NONE:    0,
	FABRIC_SECURITY_CREDENTIAL_KIND_X509:    1,
	FABRIC_SECURITY_CREDENTIAL_KIND_WINDOWS: 2,
	FABRIC_SECURITY_CREDENTIAL_KIND_CLAIMS:  3,
	FABRIC_SECURITY_CREDENTIAL_KIND_X509_2:  4,
	FABRIC_SECURITY_CREDENTIAL_KIND_INVALID: 255,
}

// enum FABRIC_REPLICA_ROLE
var FABRIC_REPLICA_ROLE = struct {
	FABRIC_REPLICA_ROLE_UNKNOWN          int32
	FABRIC_REPLICA_ROLE_NONE             int32
	FABRIC_REPLICA_ROLE_PRIMARY          int32
	FABRIC_REPLICA_ROLE_IDLE_SECONDARY   int32
	FABRIC_REPLICA_ROLE_ACTIVE_SECONDARY int32
}{
	FABRIC_REPLICA_ROLE_UNKNOWN:          0,
	FABRIC_REPLICA_ROLE_NONE:             1,
	FABRIC_REPLICA_ROLE_PRIMARY:          2,
	FABRIC_REPLICA_ROLE_IDLE_SECONDARY:   3,
	FABRIC_REPLICA_ROLE_ACTIVE_SECONDARY: 4,
}

// enum FABRIC_OPERATION_TYPE
var FABRIC_OPERATION_TYPE = struct {
	FABRIC_OPERATION_TYPE_INVALID                int32
	FABRIC_OPERATION_TYPE_NORMAL                 int32
	FABRIC_OPERATION_TYPE_END_OF_STREAM          int32
	FABRIC_OPERATION_TYPE_CREATE_ATOMIC_GROUP    int32
	FABRIC_OPERATION_TYPE_ATOMIC_GROUP_OPERATION int32
	FABRIC_OPERATION_TYPE_COMMIT_ATOMIC_GROUP    int32
	FABRIC_OPERATION_TYPE_ROLLBACK_ATOMIC_GROUP  int32
	FABRIC_OPERATION_TYPE_HAS_ATOMIC_GROUP_MASK  int32
}{
	FABRIC_OPERATION_TYPE_INVALID:                0,
	FABRIC_OPERATION_TYPE_NORMAL:                 1,
	FABRIC_OPERATION_TYPE_END_OF_STREAM:          2,
	FABRIC_OPERATION_TYPE_CREATE_ATOMIC_GROUP:    16,
	FABRIC_OPERATION_TYPE_ATOMIC_GROUP_OPERATION: 32,
	FABRIC_OPERATION_TYPE_COMMIT_ATOMIC_GROUP:    64,
	FABRIC_OPERATION_TYPE_ROLLBACK_ATOMIC_GROUP:  128,
	FABRIC_OPERATION_TYPE_HAS_ATOMIC_GROUP_MASK:  240,
}

// enum FABRIC_MOVE_COST
var FABRIC_MOVE_COST = struct {
	FABRIC_MOVE_COST_ZERO   int32
	FABRIC_MOVE_COST_LOW    int32
	FABRIC_MOVE_COST_MEDIUM int32
	FABRIC_MOVE_COST_HIGH   int32
}{
	FABRIC_MOVE_COST_ZERO:   0,
	FABRIC_MOVE_COST_LOW:    1,
	FABRIC_MOVE_COST_MEDIUM: 2,
	FABRIC_MOVE_COST_HIGH:   3,
}

// enum FABRIC_HEALTH_STATE
var FABRIC_HEALTH_STATE = struct {
	FABRIC_HEALTH_STATE_INVALID int32
	FABRIC_HEALTH_STATE_OK      int32
	FABRIC_HEALTH_STATE_WARNING int32
	FABRIC_HEALTH_STATE_ERROR   int32
	FABRIC_HEALTH_STATE_UNKNOWN int32
}{
	FABRIC_HEALTH_STATE_INVALID: 0,
	FABRIC_HEALTH_STATE_OK:      1,
	FABRIC_HEALTH_STATE_WARNING: 2,
	FABRIC_HEALTH_STATE_ERROR:   3,
	FABRIC_HEALTH_STATE_UNKNOWN: 65535,
}

// enum FABRIC_REPLICA_STATUS
var FABRIC_REPLICA_STATUS = struct {
	FABRIC_REPLICA_STATUS_INVALID int32
	FABRIC_REPLICA_STATUS_DOWN    int32
	FABRIC_REPLICA_STATUS_UP      int32
}{
	FABRIC_REPLICA_STATUS_INVALID: 0,
	FABRIC_REPLICA_STATUS_DOWN:    1,
	FABRIC_REPLICA_STATUS_UP:      2,
}

// enum FABRIC_REPLICA_SET_QUORUM_MODE
var FABRIC_REPLICA_SET_QUORUM_MODE = struct {
	FABRIC_REPLICA_SET_QUORUM_INVALID int32
	FABRIC_REPLICA_SET_WRITE_QUORUM   int32
	FABRIC_REPLICA_SET_QUORUM_ALL     int32
}{
	FABRIC_REPLICA_SET_QUORUM_INVALID: 0,
	FABRIC_REPLICA_SET_WRITE_QUORUM:   1,
	FABRIC_REPLICA_SET_QUORUM_ALL:     2,
}

// enum FABRIC_SERVICE_KIND
var FABRIC_SERVICE_KIND = struct {
	FABRIC_SERVICE_KIND_INVALID   int32
	FABRIC_SERVICE_KIND_STATELESS int32
	FABRIC_SERVICE_KIND_STATEFUL  int32
}{
	FABRIC_SERVICE_KIND_INVALID:   0,
	FABRIC_SERVICE_KIND_STATELESS: 1,
	FABRIC_SERVICE_KIND_STATEFUL:  2,
}

// enum FABRIC_SERVICE_LOAD_METRIC_WEIGHT
var FABRIC_SERVICE_LOAD_METRIC_WEIGHT = struct {
	FABRIC_SERVICE_LOAD_METRIC_WEIGHT_ZERO   int32
	FABRIC_SERVICE_LOAD_METRIC_WEIGHT_LOW    int32
	FABRIC_SERVICE_LOAD_METRIC_WEIGHT_MEDIUM int32
	FABRIC_SERVICE_LOAD_METRIC_WEIGHT_HIGH   int32
}{
	FABRIC_SERVICE_LOAD_METRIC_WEIGHT_ZERO:   0,
	FABRIC_SERVICE_LOAD_METRIC_WEIGHT_LOW:    1,
	FABRIC_SERVICE_LOAD_METRIC_WEIGHT_MEDIUM: 2,
	FABRIC_SERVICE_LOAD_METRIC_WEIGHT_HIGH:   3,
}

// enum FABRIC_EXEHOST_WORKING_FOLDER
var FABRIC_EXEHOST_WORKING_FOLDER = struct {
	FABRIC_EXEHOST_WORKING_FOLDER_INVALID      int32
	FABRIC_EXEHOST_WORKING_FOLDER_WORK         int32
	FABRIC_EXEHOST_WORKING_FOLDER_CODE_PACKAGE int32
	FABRIC_EXEHOST_WORKING_FOLDER_CODE_BASE    int32
}{
	FABRIC_EXEHOST_WORKING_FOLDER_INVALID:      0,
	FABRIC_EXEHOST_WORKING_FOLDER_WORK:         1,
	FABRIC_EXEHOST_WORKING_FOLDER_CODE_PACKAGE: 2,
	FABRIC_EXEHOST_WORKING_FOLDER_CODE_BASE:    3,
}

// enum FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND
var FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND = struct {
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_INVALID       int32
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_NONE          int32
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_EXEHOST       int32
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_DLLHOST       int32
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_CONTAINERHOST int32
}{
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_INVALID:       0,
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_NONE:          1,
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_EXEHOST:       2,
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_DLLHOST:       3,
	FABRIC_CODE_PACKAGE_ENTRY_POINT_KIND_CONTAINERHOST: 4,
}

// enum FABRIC_TRANSACTION_ISOLATION_LEVEL
var FABRIC_TRANSACTION_ISOLATION_LEVEL = struct {
	FABRIC_TRANSACTION_ISOLATION_LEVEL_DEFAULT          int32
	FABRIC_TRANSACTION_ISOLATION_LEVEL_READ_UNCOMMITTED int32
	FABRIC_TRANSACTION_ISOLATION_LEVEL_READ_COMMITTED   int32
	FABRIC_TRANSACTION_ISOLATION_LEVEL_REPEATABLE_READ  int32
	FABRIC_TRANSACTION_ISOLATION_LEVEL_SNAPSHOT         int32
	FABRIC_TRANSACTION_ISOLATION_LEVEL_SERIALIZABLE     int32
}{
	FABRIC_TRANSACTION_ISOLATION_LEVEL_DEFAULT:          0,
	FABRIC_TRANSACTION_ISOLATION_LEVEL_READ_UNCOMMITTED: 1,
	FABRIC_TRANSACTION_ISOLATION_LEVEL_READ_COMMITTED:   2,
	FABRIC_TRANSACTION_ISOLATION_LEVEL_REPEATABLE_READ:  3,
	FABRIC_TRANSACTION_ISOLATION_LEVEL_SNAPSHOT:         4,
	FABRIC_TRANSACTION_ISOLATION_LEVEL_SERIALIZABLE:     5,
}

// enum FABRIC_STORE_BACKUP_OPTION
var FABRIC_STORE_BACKUP_OPTION = struct {
	FABRIC_STORE_BACKUP_OPTION_FULL               int32
	FABRIC_STORE_BACKUP_OPTION_INCREMENTAL        int32
	FABRIC_STORE_BACKUP_OPTION_TRUNCATE_LOGS_ONLY int32
}{
	FABRIC_STORE_BACKUP_OPTION_FULL:               1,
	FABRIC_STORE_BACKUP_OPTION_INCREMENTAL:        2,
	FABRIC_STORE_BACKUP_OPTION_TRUNCATE_LOGS_ONLY: 3,
}

// enum FABRIC_CODE_PACKAGE_EVENT_TYPE
var FABRIC_CODE_PACKAGE_EVENT_TYPE = struct {
	FABRIC_CODE_PACKAGE_EVENT_TYPE_INVALID      int32
	FABRIC_CODE_PACKAGE_EVENT_TYPE_START_FAILED int32
	FABRIC_CODE_PACKAGE_EVENT_TYPE_STARTED      int32
	FABRIC_CODE_PACKAGE_EVENT_TYPE_READY        int32
	FABRIC_CODE_PACKAGE_EVENT_TYPE_HEALTH       int32
	FABRIC_CODE_PACKAGE_EVENT_TYPE_STOPPED      int32
	FABRIC_CODE_PACKAGE_EVENT_TYPE_TERMINATED   int32
}{
	FABRIC_CODE_PACKAGE_EVENT_TYPE_INVALID:      0,
	FABRIC_CODE_PACKAGE_EVENT_TYPE_START_FAILED: 1,
	FABRIC_CODE_PACKAGE_EVENT_TYPE_STARTED:      2,
	FABRIC_CODE_PACKAGE_EVENT_TYPE_READY:        3,
	FABRIC_CODE_PACKAGE_EVENT_TYPE_HEALTH:       4,
	FABRIC_CODE_PACKAGE_EVENT_TYPE_STOPPED:      5,
	FABRIC_CODE_PACKAGE_EVENT_TYPE_TERMINATED:   6,
}

// enum FABRIC_LOCAL_STORE_KIND
var FABRIC_LOCAL_STORE_KIND = struct {
	FABRIC_LOCAL_STORE_KIND_INVALID int32
	FABRIC_LOCAL_STORE_KIND_ESE     int32
}{
	FABRIC_LOCAL_STORE_KIND_INVALID: 0,
	FABRIC_LOCAL_STORE_KIND_ESE:     1,
}

// enum FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE
var FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE = struct {
	FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE_INVALID                   int32
	FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE_NONE                      int32
	FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE_NON_BLOCKING_QUORUM_ACKED int32
	FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE_BLOCK_SECONDARY_ACK       int32
}{
	FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE_INVALID:                   0,
	FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE_NONE:                      1,
	FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE_NON_BLOCKING_QUORUM_ACKED: 2,
	FABRIC_KEY_VALUE_STORE_NOTIFICATION_MODE_BLOCK_SECONDARY_ACK:       3,
}
