package fabriccommon

// enum FABRIC_REPLICA_ROLE
var FABRIC_REPLICA_ROLE = struct {
	FABRIC_REPLICA_ROLE_UNKNOWN          int32
	FABRIC_REPLICA_ROLE_NONE             int32
	FABRIC_REPLICA_ROLE_PRIMARY          int32
	FABRIC_REPLICA_ROLE_IDLE_SECONDARY   int32
	FABRIC_REPLICA_ROLE_ACTIVE_SECONDARY int32
}{
	FABRIC_REPLICA_ROLE_UNKNOWN:          0,
	FABRIC_REPLICA_ROLE_NONE:             1,
	FABRIC_REPLICA_ROLE_PRIMARY:          2,
	FABRIC_REPLICA_ROLE_IDLE_SECONDARY:   3,
	FABRIC_REPLICA_ROLE_ACTIVE_SECONDARY: 4,
}

// enum FABRIC_X509_STORE_LOCATION
var FABRIC_X509_STORE_LOCATION = struct {
	FABRIC_X509_STORE_LOCATION_INVALID      int32
	FABRIC_X509_STORE_LOCATION_CURRENTUSER  int32
	FABRIC_X509_STORE_LOCATION_LOCALMACHINE int32
}{
	FABRIC_X509_STORE_LOCATION_INVALID:      0,
	FABRIC_X509_STORE_LOCATION_CURRENTUSER:  1,
	FABRIC_X509_STORE_LOCATION_LOCALMACHINE: 2,
}
